set_property PACKAGE_PIN F15 [get_ports A]
set_property PACKAGE_PIN V10 [get_ports B]
set_property PACKAGE_PIN R10 [get_ports C]
set_property PACKAGE_PIN T16 [get_ports D]
set_property PACKAGE_PIN T8 [get_ports Q]
set_property IOSTANDARD LVCMOS18 [get_ports A]
set_property IOSTANDARD LVCMOS18 [get_ports C]
set_property IOSTANDARD LVCMOS18 [get_ports B]
set_property IOSTANDARD LVCMOS18 [get_ports D]
set_property IOSTANDARD LVCMOS18 [get_ports Q]

