set_property PACKAGE_PIN F15 [get_ports A1]
set_property PACKAGE_PIN T16 [get_ports A2]
set_property PACKAGE_PIN E16 [get_ports B1]
set_property PACKAGE_PIN R10 [get_ports B2]
set_property PACKAGE_PIN T6 [get_ports Q1]
set_property PACKAGE_PIN R8 [get_ports Q2]
set_property PACKAGE_PIN P4 [get_ports S]
set_property IOSTANDARD LVCMOS18 [get_ports A1]
set_property IOSTANDARD LVCMOS18 [get_ports A2]
set_property IOSTANDARD LVCMOS18 [get_ports B1]
set_property IOSTANDARD LVCMOS18 [get_ports B2]
set_property IOSTANDARD LVCMOS18 [get_ports Q1]
set_property IOSTANDARD LVCMOS18 [get_ports Q2]
set_property IOSTANDARD LVCMOS18 [get_ports S]

