version: '3.8'

services:
  task-management:
    build:
      context: ./task-management
    ports:
      - "3000:3000"
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
    ports:
      - "3010:3010"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-db:3306/user_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - user-db
      - kafka
    networks:
      - app-network

  user-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service
    ports:
      - "3307:3306"
    networks:
      - app-network

  task-service:
    build:
      context: ./task-service
    ports:
      - "3011:3011"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://task-db:3306/task_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - task-db
      - kafka
    networks:
      - app-network

  task-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_service
    ports:
      - "3308:3306"
    networks:
      - app-network

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "3012:3012"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
